In [4]:
import numpy as np

In [20]:
#0D
a=np.array(45)

#1D
b=np.array([1,2,3])

#2D
c=np.array([[1,2,3],[4,5,6]])

#3D
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,0,0]]])

#float
f=np.array([1.1,2.2,3.3])

#ndim check dimmention

print(a)
print(a.ndim)
print(b)
print(b.ndim)
print(c)
print(c.ndim)
print(d)
print(d.ndim)

#higher dimension array declaration(xth dimension)
#arr=np.array([],ndim=x)

45
0
[1 2 3]
1
[[1 2 3]
 [4 5 6]]
2
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 0 0]]]
3


In [23]:
#type
print(type(d))

#data type
print(c.dtype)

#datatype declaration
#arr=np.array([],dtype='')
#i,b,u,f,c,M(time),O,S,U,V

print(f)
#type conversion
newf=f.astype('i')
print(newf)

<class 'numpy.ndarray'>
int32
[1.1 2.2 3.3]
[1 2 3]


In [26]:
#copy vs view
x=b.copy()
y=b.view()
b[0]=-1
print(b)
print(x)
print(y)



[-1  2  3]
[-1  2  3]
[-1  2  3]
None
[-1  2  3]


In [27]:
#wether array owns data or not
print(x.base)
print(y.base)

None
[-1  2  3]


In [31]:
#shape
print(c.shape)

#shape change
newb=b.reshape(3,1)
print(newb)

#pass -1 if unknown dimension(can be used to flattern reshape(-1))

(2, 3)
[[-1]
 [ 2]
 [ 3]]


In [53]:
#random
x=np.random.randint(10)
print(x)
#random float
x=np.random.rand()
print(x)
#random array
#1D
x=np.random.randint(10,size=(3))
print(x)
#2D
x=np.random.randint(10,size=(2,2))
print(x)
#from array
x=np.random.choice([2,5,4])
print(x)

-0.4480736161291701
3.141592653589793
0
0.18832568402835026
[3 7 0]
[[0 3]
 [0 1]]
4


In [57]:
#toss
v=np.random.choice(['head','tail'])
print(v)

tail


In [64]:
#dice
v=np.random.choice([1,2,3,4,5,6],p=[0.2,0.15,0.15,0.25,0.17,0.08])
print(v)

#test for 100 results
v=np.random.choice([1,2,3,4,5,6],p=[0.2,0.15,0.15,0.25,0.17,0.08],size=(100))
print(v)

6
[2 3 5 1 1 4 2 2 2 4 2 3 2 5 3 4 6 5 2 1 2 4 1 6 4 2 4 1 3 5 6 5 4 1 2 5 5
 1 3 4 5 3 4 2 1 1 4 1 4 4 5 5 4 4 5 6 1 1 1 2 2 1 6 6 3 5 4 3 1 2 4 2 1 1
 1 1 2 4 4 5 3 3 3 1 4 3 4 6 4 5 4 4 3 5 1 1 4 4 4 4]


In [71]:
shuffling
v=np.array([1,2,3,4,5,6])
np.random.shuffle(v)
print(v)

[6 2 5 1 3 4]


In [81]:
#permutation
v=np.array([1,2,3,4,5,6])
print(np.random.permutation(v))

[6 3 1 2 4 5]


In [91]:
print(np.cos(90))
print(np.pi)
print(np.e)
print(np.sqrt(16))
print(np.square(16))
print(np.math.factorial(5))

-0.4480736161291701
3.141592653589793
2.718281828459045
4.0
256
120
